services:
  pollimage:
    build: .
    container_name: front_pollimage
    networks:
      - proxynet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pollimage.rule=Host(`dashboard.robinweb.it`)"
      - "traefik.http.routers.pollimage.entrypoints=https"
      - "traefik.http.routers.pollimage.tls=true"
 #     - "traefik.http.routers.pollimage.tls.certresolver=cloudflare"
      - "traefik.http.services.pollimage.loadbalancer.server.port=8081"
      # Redirect HTTP -> HTTPS
      - "traefik.http.routers.pollimage-http.rule=Host(`dashboard.robinweb.it`)"
      - "traefik.http.routers.pollimage-http.entrypoints=http"
      - "traefik.http.routers.pollimage-http.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
    environment:
      NODE_ENV: production
      PORT: 8081
      DB_PATH: /data/db.sqlite
    volumes:
      - /var/job/data/db.sqlite:/data/db.sqlite:ro
    restart: unless-stopped

networks:
  proxynet:
    external: true
